### ISSUE TITLE
Pipeline ends with "ValueError: array must not contain infs or NaNs"

### ISSUE THREAD

**Issue by svw26** [mattyowl/RSSMOSPipeline#20]
Hiya Matt,

Hope you're doing well! I'm reducing some RSS-longslit data, with a couple of nights from 2020 :S running into difficulties. In both cases ( 2020-1-MLT-008.20200919 and 2020-1-MLT-008.20200920 ) the terminal output quotes lots of RuntimeWarnings, followed by a ValueError, like so:

```
2022-10-11 11:25:54,997 - RSSMOSPipeline - INFO - reduced/G4Jy 148_PL0200N001/rwcmbxgpP202009190086.fits
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py:763: RuntimeWarning: invalid value encountered in less
  chipGapMask=np.array(np.less(data, lowMaskValue), dtype = float)  # flags chip gaps as noise
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/numpy/lib/function_base.py:3250: RuntimeWarning: Invalid value encountered in median for 47 results
  r = func(a, **kwargs)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py:1523: RuntimeWarning: invalid value encountered in less
  prof[np.less(prof, 0)]=0.
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py:1528: RuntimeWarning: invalid value encountered in less
  mask=np.less(abs(prof-mean), sigmaCut*sigma)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py:1537: RuntimeWarning: invalid value encountered in less
  prof[np.less(prof, 0)]=0.
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py:2205: RuntimeWarning: invalid value encountered in less
  mask=np.less(abs(data-mean), sigmaCut*sigma)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py:2211: RuntimeWarning: invalid value encountered in greater
  mask=np.greater(abs(data-mean), sigmaCut*sigma)
Traceback (most recent call last):
  File "/Users/sarahwhite/anaconda/envs/rssmospipeline_master/bin/rss_mos_reducer", line 170, in <module>
    iterativeMethod = iterativeMethod, subFrac = subFrac)
  File "/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py", line 2035, in extractAndStackSpectra
    signal, sky, mData=weightedExtraction(data)
  File "/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/RSSMOSPipeline/RSSMOSTools.py", line 1826, in weightedExtraction
    x, R=optimize.nnls(w, v)
  File "/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/scipy/optimize/nnls.py", line 43, in nnls
    A, b = map(asarray_chkfinite, (A, b))
  File "/Users/sarahwhite/anaconda/envs/rssmospipeline_master/lib/python3.5/site-packages/numpy/lib/function_base.py", line 461, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

Please what do you suggest to fix/work around this?

Many thanks,
Sarah x

**Comment by mattyowl** [comment]
Hi Sarah,

I've checked some changes into the master branch, which fixes some issues with how the chip gap masking and flat fielding works (should be more robust now). After doing that, your data ran through the pipeline ok. Please take a look. I might just put this out as a new tagged release.

Cheers
Matt

**Comment by mattyowl** [comment]
Changes are in 0.4.0 (now on PyPI) - please let me know if you have any more issues.
